POST https://garamante.it/API/login.php
Content-Type: application/x-www-form-urlencoded

username=test&password=test

###

POST https://garamante.it/API/register.php
Content-Type: application/x-www-form-urlencoded

username=test&password=test

###

POST https://garamante.it/API/getPartyData.php
Content-Type: application/x-www-form-urlencoded

party_id=4e327eb3-7cf0-4b53-bdf4-c334d56f5470